import type { Metadata } from "next";
import "./globals.css";
import { languageTag } from "@/src/paraglide/runtime";
import { LanguageProvider } from "@inlang/paraglide-next";
import { Playfair_Display } from "next/font/google";
import localFont from "next/font/local";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

const styleScript = localFont({
	src: "./fonts/StyleScript-Regular.ttf",
	variable: "--font-style-script",
});

const playfairDisplay = Playfair_Display({
	subsets: ["latin"],
	weight: ["400", "500", "600"],
	variable: "--font-playfair-display",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const language = languageTag();
	return (
		<LanguageProvider>
			<html lang={language} dir={language === "ar" ? "rtl" : "ltr"}>
				<body>
					<main
						className={`${geistSans.variable} ${geistMono.variable} ${styleScript.variable} ${playfairDisplay.variable} antialiased`}
					>
						{children}
					</main>
				</body>
			</html>
		</LanguageProvider>
	);
}
